### ISSUE TITLE
能不能把网盘里的解析高速链接那个按钮去除.网盘解析高速链接的作者关项目了

### ISSUE THREAD

**Issue by aierlma** [Xwudao/good_gm_script#1]
能不能把网盘里的解析高速链接那个按钮去除，纯小白。。。
![批注 2020-09-05 181249](https://user-images.githubusercontent.com/55280375/92302981-703d6180-efa3-11ea-845c-f25188207af7.jpg)

**Comment by Xwudao** [comment]
之前更新的版本已关闭！
